# Generated by Django 4.1.6 on 2023-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0005_user_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(default='aa.pdf', upload_to='resume'),
            preserve_default=False,
        ),
    ]
