# Generated by Django 4.1.6 on 2023-02-17 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0007_user_dob_user_employee_address_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEmployementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_emp', models.CharField(max_length=30)),
                ('work_exp_year', models.CharField(max_length=30)),
                ('work_exp_month', models.CharField(max_length=30)),
                ('current_company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pervious_company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('key_skills', models.TextField()),
                ('work_type', models.CharField(max_length=40)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=40, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserEmployement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
