# Generated by Django 4.1.6 on 2023-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0008_useremployementdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FillEmpstatus',
            field=models.BooleanField(default=False),
        ),
    ]
