# Generated by Django 4.1.6 on 2023-02-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0010_jobcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='job',
            new_name='name',
        ),
    ]
