# Generated by Django 4.1.6 on 2023-02-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0013_user_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcat', to='call4jobapp.jobcategory'),
        ),
    ]
