# Generated by Django 4.1.6 on 2023-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0017_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_job',
            name='assign_job_status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
