# Generated by Django 4.1.6 on 2023-03-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0020_cms_pages_slug_alter_cms_pages_heading1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
