# Generated by Django 4.1.6 on 2023-03-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0022_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blogCategory', to='call4jobapp.blogcategory'),
            preserve_default=False,
        ),
    ]
