# Generated by Django 4.1.6 on 2023-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0026_user_country_code_user_office_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(default='2021-03-27', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mob_no_verified',
            field=models.BooleanField(default=False),
        ),
    ]
