# Generated by Django 4.1.6 on 2023-04-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0027_user_auth_token_user_device_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
