# Generated by Django 4.1.6 on 2023-04-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0028_remove_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
