# Generated by Django 4.1.6 on 2023-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0030_rename_email_verified_user_social_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fcm_token',
            new_name='device_token',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no_verified',
            field=models.BooleanField(default=False),
        ),
    ]
