# Generated by Django 4.1.6 on 2023-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0032_alter_blog_options_alter_cms_pages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'permissions': (('sidebar_job_catgory', 'Can sidebar job_catgory'),)},
        ),
    ]
