# Generated by Django 4.1.6 on 2023-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0034_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployementdetails',
            name='it_skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremployementdetails',
            name='skills_used',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
