# Generated by Django 4.1.6 on 2023-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0035_useremployementdetails_it_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployementdetails',
            name='joining_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremployementdetails',
            name='leaving_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
