# Generated by Django 4.2 on 2023-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0037_alter_useremployementdetails_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='soft_del_status',
            field=models.BooleanField(default=False),
        ),
    ]
