# Generated by Django 4.2 on 2023-06-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0038_alter_user_image'),
        ('call4jobapp', '0038_user_soft_del_status'),
    ]

    operations = [
    ]
