# Generated by Django 4.2 on 2023-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0039_merge_0038_alter_user_image_0038_user_soft_del_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployementdetails',
            name='it_skills',
        ),
        migrations.RemoveField(
            model_name='useremployementdetails',
            name='skills_used',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='age_criteria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='emp_gender',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_opportunity',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='notice_period',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
