# Generated by Django 4.2 on 2023-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0040_remove_useremployementdetails_it_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployementdetails',
            name='skills_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
