# Generated by Django 4.1.6 on 2023-06-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0042_useremployementdetails_it_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcategorycompany', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('sidebar_jobcategory', 'Can sidebar jobcategory'),),
            },
        ),
    ]
