# Generated by Django 4.1.6 on 2023-06-16 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0043_jobcategorycompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryOptionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcategorycompanyoption', to='call4jobapp.jobcategorycompany')),
            ],
            options={
                'permissions': (('sidebar_jobcategoryoption', 'Can sidebar jobcategoryoption'),),
            },
        ),
    ]
