# Generated by Django 4.1.6 on 2023-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0044_jobcategoryoptioncompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='device_token',
            new_name='auth_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_address',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='social_login',
            new_name='login_source',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
