# Generated by Django 4.1.6 on 2023-06-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call4jobapp', '0045_rename_device_token_user_auth_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
